trigger:
  branches:
    include:
    - master
  paths:
    include:
    - environment_setup/arm-templates/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devopsforai-aml-vg


steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'AzureResourceConnection'
    action: 'DeleteRG'
    resourceGroupName: '$(RESOURCE_GROUP)'
    location: $(LOCATION)
  displayName: 'Delete resources in Azure'

  